/* eslint-disable */
require('./arrow-down')
require('./arrow')
require('./camera')
require('./edit-pen')
require('./facebook-logo')
require('./instagram')
require('./like')
require('./linkedin-letters')
require('./location-pin')
require('./search')
require('./twitter')
require('./video-camera')
